### モジュール　Numpyの使い方

---

Numpyは行列計算や基本統計量の計算など、Pythonにおける計算を勘弁に実施するためのモジュールである。

【Numpyでできること】（代表例）
1. 数字生成
2. 基本統計量の計算
3. 行列の計算

Link to: [Numpy official page](https://numpy.org)

In [2]:
#### モジュールのインポート
import numpy as np

ここで```as np```は```numpy```を略式で書くことを示している。モジュールは通常、モジュール名にメソッドを追加して記述するが、モジュール名が長いときはイチイチ書くのが面倒なので略すことができる。これはどのモジュールも同じです。基本的に、```as```以下は自分で好きなように定義することができるが、頻繁に使われるモジュール（```numpy, pandas, matplotlib.pyplot```）は世の中的に暗黙の了解的に使われている短縮後が存在している。

- numpy $\rightarrow$ np
- pandas $\rightarrow$ pd
- matplotlib.pyplot $\rightarrow$ plt

---

#### 数字生成

計算するときに頻度高く使うことになります。当面は以下の２つのメソッドを覚えれば十分です。

|目的||メソッド|
|---||---|
|数字を線形的に等間隔で刻む||Numpy.linspace(始まりの数,終わりの数,刻みの数)|
|数字を指数的に等間隔で刻む||Numpy.logspace(始まりのべき乗数,終わりのべき乗数,底)|

In [3]:
# 1から10まで100刻んで表示する
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [10]:
# 7^1から7^3まで100刻んでを表示する
np.logspace(1,3,100,base=7)

array([  7.        ,   7.28065962,   7.57257207,   7.87618853,
         8.19197825,   8.52042932,   8.86204939,   9.21736645,
         9.58692967,   9.97131025,  10.37110227,  10.78692364,
        11.21941705,  11.66925096,  12.13712061,  12.62374913,
        13.12988865,  13.65632144,  14.20386115,  14.77335405,
        15.36568032,  15.98175546,  16.62253166,  17.28899929,
        17.98218843,  18.70317046,  19.4530597 ,  20.23301518,
        21.04424237,  21.88799509,  22.76557743,  23.67834576,
        24.62771083,  25.61513997,  26.64215932,  27.71035622,
        28.82138165,  29.9769528 ,  31.17885568,  32.42894793,
        33.72916167,  35.08150649,  36.48807252,  37.95103375,
        39.47265128,  41.05527689,  42.70135666,  44.41343473,
        46.19415726,  48.04627649,  49.97265502,  51.97627021,
        54.06021881,  56.22772174,  58.48212902,  60.82692503,
        63.26573384,  65.80232481,  68.44061845,  71.18469244,
        74.03878797,  77.00731626,  80.09486542,  83.30

---

#### 基本統計量の計算

膨大な数の計算メソッドがあるので、まずは以下のメソッドに慣れればOK。他のメソッドについては、都度、google等で検索をかけて使い方を調べるで十分です。

|目的||メソッド|
|---||---|
|平均を計算する||```Numpy.average()```|
|分散を計算する||```Numpy.var()```|
|標準偏差を計算する||```Numpy.std()```|

オススメのページ：[note.nkmk.me](https://note.nkmk.me/python-numpy-ndarray-sum-mean-axis/)

In [5]:
# 例として、1-10までの数字を100個生成する
X = np.linspace(0,100,100)

In [6]:
print(X)

[  0.           1.01010101   2.02020202   3.03030303   4.04040404
   5.05050505   6.06060606   7.07070707   8.08080808   9.09090909
  10.1010101   11.11111111  12.12121212  13.13131313  14.14141414
  15.15151515  16.16161616  17.17171717  18.18181818  19.19191919
  20.2020202   21.21212121  22.22222222  23.23232323  24.24242424
  25.25252525  26.26262626  27.27272727  28.28282828  29.29292929
  30.3030303   31.31313131  32.32323232  33.33333333  34.34343434
  35.35353535  36.36363636  37.37373737  38.38383838  39.39393939
  40.4040404   41.41414141  42.42424242  43.43434343  44.44444444
  45.45454545  46.46464646  47.47474747  48.48484848  49.49494949
  50.50505051  51.51515152  52.52525253  53.53535354  54.54545455
  55.55555556  56.56565657  57.57575758  58.58585859  59.5959596
  60.60606061  61.61616162  62.62626263  63.63636364  64.64646465
  65.65656566  66.66666667  67.67676768  68.68686869  69.6969697
  70.70707071  71.71717172  72.72727273  73.73737374  74.74747475
  75.7575757

In [12]:
# 平均値計算
np.average(X)

50.5

In [13]:
# 分散値計算
np.var(X)

833.25

In [14]:
# 標準偏差計算
np.std(X)

28.86607004772212

---

#### 行列の計算

Pythonにおける行列は『多次元の配列』と考える。これが２次元のものを特に行列という。

- listの中のlist $\rightarrow$ ```[[1,2,3,4,5],[10,20,30,40,50]]```（list型）
- listの中のlistを行列型で表示 $\rightarrow$ ```np.array([[1,2,3,4,5],[10,20,30,40,50]])```（行列型）

数値計算においては行列で計算することで計算速度を格段に向上することができる。普段使うことはさほど多くないので、基本的な四則演算のみ覚えればOKです。

例えば、行列AとBが存在するとき、それぞれの四則演算を計算してみる。

$$
A = \left(
\begin{matrix}
1 & 2 \\
3 & 4
\end{matrix}
\right)
$$

$$
B = \left(
\begin{matrix}
10 & 20 \\
30 & 40
\end{matrix}
\right)
$$

In [17]:
A = np.array([[1,2],[3,4]])

In [18]:
B = np.array([[10,20],[30,40]])

In [19]:
B + A

array([[11, 22],
       [33, 44]])

In [20]:
B - A

array([[ 9, 18],
       [27, 36]])

In [21]:
B * A

array([[ 10,  40],
       [ 90, 160]])

In [22]:
B / A

array([[10., 10.],
       [10., 10.]])

Pythonにおける乗算、割算については『要素どうしの演算』になる。

一般的な行列演算は```numpy.dot```を使うことに注意する。

In [24]:
np.dot(B,A)

array([[ 70, 100],
       [150, 220]])

In [25]:
np.dot(A,B)

array([[ 70, 100],
       [150, 220]])

#### おまけ１

行列からの要素抽出：```[行][列]```で指定

In [27]:
A[0][1] #0行1列目の要素の抽出

2

#### おまけ２
画像は何丁目何番地（行と列）に加えて色味を表す次元が存在する。

- 白黒画像：```np.array(pixel行,pixel列,(0 or 1))```
- グレースケール画像：```np.array(pixel行,pixel列,(0~255))```
- RGB画像：```np.array(pixel行, pixel列, ((0~255),(0~255),(0~255)))```$\leftarrow$色味は（赤,緑,青）の順番

---

演習問題１：

1. 3から40までを線形的に等間隔に200刻み変数aに入れなさい。
2. aを5倍しなさい。
3. aの平均、分散、標準偏差を求めなさい

演習問題２：

上記で定義した行列Aの行列式を求めなさい。