In [ ]:
import numpy as np

数字生成

In [ ]:
#1から100まで刻んで表示する
np.linspace(1, 10, 100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [ ]:
# 7^1から7^3まで100刻んでを表示する
np.logspace(1, 3, 100, base=7)

array([  7.        ,   7.28065962,   7.57257207,   7.87618853,
         8.19197825,   8.52042932,   8.86204939,   9.21736645,
         9.58692967,   9.97131025,  10.37110227,  10.78692364,
        11.21941705,  11.66925096,  12.13712061,  12.62374913,
        13.12988865,  13.65632144,  14.20386115,  14.77335405,
        15.36568032,  15.98175546,  16.62253166,  17.28899929,
        17.98218843,  18.70317046,  19.4530597 ,  20.23301518,
        21.04424237,  21.88799509,  22.76557743,  23.67834576,
        24.62771083,  25.61513997,  26.64215932,  27.71035622,
        28.82138165,  29.9769528 ,  31.17885568,  32.42894793,
        33.72916167,  35.08150649,  36.48807252,  37.95103375,
        39.47265128,  41.05527689,  42.70135666,  44.41343473,
        46.19415726,  48.04627649,  49.97265502,  51.97627021,
        54.06021881,  56.22772174,  58.48212902,  60.82692503,
        63.26573384,  65.80232481,  68.44061845,  71.18469244,
        74.03878797,  77.00731626,  80.09486542,  83.30

In [ ]:
a = np.linspace(3, 40, 200)
a

array([ 3.        ,  3.18592965,  3.3718593 ,  3.55778894,  3.74371859,
        3.92964824,  4.11557789,  4.30150754,  4.48743719,  4.67336683,
        4.85929648,  5.04522613,  5.23115578,  5.41708543,  5.60301508,
        5.78894472,  5.97487437,  6.16080402,  6.34673367,  6.53266332,
        6.71859296,  6.90452261,  7.09045226,  7.27638191,  7.46231156,
        7.64824121,  7.83417085,  8.0201005 ,  8.20603015,  8.3919598 ,
        8.57788945,  8.7638191 ,  8.94974874,  9.13567839,  9.32160804,
        9.50753769,  9.69346734,  9.87939698, 10.06532663, 10.25125628,
       10.43718593, 10.62311558, 10.80904523, 10.99497487, 11.18090452,
       11.36683417, 11.55276382, 11.73869347, 11.92462312, 12.11055276,
       12.29648241, 12.48241206, 12.66834171, 12.85427136, 13.04020101,
       13.22613065, 13.4120603 , 13.59798995, 13.7839196 , 13.96984925,
       14.15577889, 14.34170854, 14.52763819, 14.71356784, 14.89949749,
       15.08542714, 15.27135678, 15.45728643, 15.64321608, 15.82

In [ ]:
a = a * 5
a

array([ 15.        ,  15.92964824,  16.85929648,  17.78894472,
        18.71859296,  19.64824121,  20.57788945,  21.50753769,
        22.43718593,  23.36683417,  24.29648241,  25.22613065,
        26.15577889,  27.08542714,  28.01507538,  28.94472362,
        29.87437186,  30.8040201 ,  31.73366834,  32.66331658,
        33.59296482,  34.52261307,  35.45226131,  36.38190955,
        37.31155779,  38.24120603,  39.17085427,  40.10050251,
        41.03015075,  41.95979899,  42.88944724,  43.81909548,
        44.74874372,  45.67839196,  46.6080402 ,  47.53768844,
        48.46733668,  49.39698492,  50.32663317,  51.25628141,
        52.18592965,  53.11557789,  54.04522613,  54.97487437,
        55.90452261,  56.83417085,  57.7638191 ,  58.69346734,
        59.62311558,  60.55276382,  61.48241206,  62.4120603 ,
        63.34170854,  64.27135678,  65.20100503,  66.13065327,
        67.06030151,  67.98994975,  68.91959799,  69.84924623,
        70.77889447,  71.70854271,  72.63819095,  73.56

In [ ]:
#平均値
np.average(a)


107.5

In [ ]:
#分散値
np.var(a)


2880.747487437186

In [ ]:
#標準偏差
np.std(a)


53.6725953111752

In [ ]:
a + 5

array([ 20.        ,  20.92964824,  21.85929648,  22.78894472,
        23.71859296,  24.64824121,  25.57788945,  26.50753769,
        27.43718593,  28.36683417,  29.29648241,  30.22613065,
        31.15577889,  32.08542714,  33.01507538,  33.94472362,
        34.87437186,  35.8040201 ,  36.73366834,  37.66331658,
        38.59296482,  39.52261307,  40.45226131,  41.38190955,
        42.31155779,  43.24120603,  44.17085427,  45.10050251,
        46.03015075,  46.95979899,  47.88944724,  48.81909548,
        49.74874372,  50.67839196,  51.6080402 ,  52.53768844,
        53.46733668,  54.39698492,  55.32663317,  56.25628141,
        57.18592965,  58.11557789,  59.04522613,  59.97487437,
        60.90452261,  61.83417085,  62.7638191 ,  63.69346734,
        64.62311558,  65.55276382,  66.48241206,  67.4120603 ,
        68.34170854,  69.27135678,  70.20100503,  71.13065327,
        72.06030151,  72.98994975,  73.91959799,  74.84924623,
        75.77889447,  76.70854271,  77.63819095,  78.56

In [ ]:
a - 5

array([ 10.        ,  10.92964824,  11.85929648,  12.78894472,
        13.71859296,  14.64824121,  15.57788945,  16.50753769,
        17.43718593,  18.36683417,  19.29648241,  20.22613065,
        21.15577889,  22.08542714,  23.01507538,  23.94472362,
        24.87437186,  25.8040201 ,  26.73366834,  27.66331658,
        28.59296482,  29.52261307,  30.45226131,  31.38190955,
        32.31155779,  33.24120603,  34.17085427,  35.10050251,
        36.03015075,  36.95979899,  37.88944724,  38.81909548,
        39.74874372,  40.67839196,  41.6080402 ,  42.53768844,
        43.46733668,  44.39698492,  45.32663317,  46.25628141,
        47.18592965,  48.11557789,  49.04522613,  49.97487437,
        50.90452261,  51.83417085,  52.7638191 ,  53.69346734,
        54.62311558,  55.55276382,  56.48241206,  57.4120603 ,
        58.34170854,  59.27135678,  60.20100503,  61.13065327,
        62.06030151,  62.98994975,  63.91959799,  64.84924623,
        65.77889447,  66.70854271,  67.63819095,  68.56

In [ ]:
a * 5

array([  75.        ,   79.64824121,   84.29648241,   88.94472362,
         93.59296482,   98.24120603,  102.88944724,  107.53768844,
        112.18592965,  116.83417085,  121.48241206,  126.13065327,
        130.77889447,  135.42713568,  140.07537688,  144.72361809,
        149.3718593 ,  154.0201005 ,  158.66834171,  163.31658291,
        167.96482412,  172.61306533,  177.26130653,  181.90954774,
        186.55778894,  191.20603015,  195.85427136,  200.50251256,
        205.15075377,  209.79899497,  214.44723618,  219.09547739,
        223.74371859,  228.3919598 ,  233.04020101,  237.68844221,
        242.33668342,  246.98492462,  251.63316583,  256.28140704,
        260.92964824,  265.57788945,  270.22613065,  274.87437186,
        279.52261307,  284.17085427,  288.81909548,  293.46733668,
        298.11557789,  302.7638191 ,  307.4120603 ,  312.06030151,
        316.70854271,  321.35678392,  326.00502513,  330.65326633,
        335.30150754,  339.94974874,  344.59798995,  349.24623

In [ ]:
a / 5

array([ 3.        ,  3.18592965,  3.3718593 ,  3.55778894,  3.74371859,
        3.92964824,  4.11557789,  4.30150754,  4.48743719,  4.67336683,
        4.85929648,  5.04522613,  5.23115578,  5.41708543,  5.60301508,
        5.78894472,  5.97487437,  6.16080402,  6.34673367,  6.53266332,
        6.71859296,  6.90452261,  7.09045226,  7.27638191,  7.46231156,
        7.64824121,  7.83417085,  8.0201005 ,  8.20603015,  8.3919598 ,
        8.57788945,  8.7638191 ,  8.94974874,  9.13567839,  9.32160804,
        9.50753769,  9.69346734,  9.87939698, 10.06532663, 10.25125628,
       10.43718593, 10.62311558, 10.80904523, 10.99497487, 11.18090452,
       11.36683417, 11.55276382, 11.73869347, 11.92462312, 12.11055276,
       12.29648241, 12.48241206, 12.66834171, 12.85427136, 13.04020101,
       13.22613065, 13.4120603 , 13.59798995, 13.7839196 , 13.96984925,
       14.15577889, 14.34170854, 14.52763819, 14.71356784, 14.89949749,
       15.08542714, 15.27135678, 15.45728643, 15.64321608, 15.82